spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ocristian/microservices-pla.git
          username: ${GIT_USER}
          password: ${GIT_PASS}
          search-paths:
            - "pla-config-properties/{application}/{profile}"